# SITE CONFIGURATION
title: Sleek # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://kchalkowski.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
